blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns =[
    path('',views.PostList.as_view(),name='post_list'),
    path('detail/<int:pk>/',views.PostDetail.as_view(),name='post_detail'),
    path('comment/<int:pk>',views.CommentCreate.as_view(),name='comment_create'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diaries/',include('diaries.urls')),
    path('reviews/',include('reviews.urls')),
    path('contact/',include('contact.urls')),
    path('video/',include('video.urls')),
    path('blog/',include('blog.urls')),
    path('',include('myprofile.urls')),
]

urlpatterns += static(settings.MEDIA_URL,docment_root=settings.MEDIA_ROOT)

reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'

urlpatterns =[
    path("",views.ReviewList.as_view(),name='review_list'),
    path("detail/<int:pk>/",views.ReviewDetail.as_view(),name='review_detail'),
    path("create/",views.ReviewCreate.as_view(),name='review_create'),
    path("update/<int:pk>/",views.ReviewUpdate.as_view(),name='review_update'),
    path("delete/<int:pk>/",views.ReviewDelete.as_view(),name='review_delete'),
]

reviews/models.py
from django.db import models
from django.utils import timezone 

# Create your models here.
class Review(models.Model):
    
    STARS = (
        (1,"☆"),
        (2,"☆☆"),
        (3,"☆☆☆"),
        (4,"☆☆☆☆"),
        (5,"☆☆☆☆☆"),
    )

    store_name = models.CharField("店名",max_length=255)
    title = models.CharField("タイトル",max_length=255)
    text = models.TextField("口コミテキスト",blank=True)
    stars = models.IntegerField("星の数",choices=STARS)
    created_at = models.DateTimeField('作成日',default=timezone.now)

    def __str__(self):
        return self.title

reviews/forms.py
from django import forms
from .models import Review

class ReviewCreateForm(forms.ModelForm):

    class Meta:
        model = Review
        exclude = ('created_at',)


reviews/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Review
from .forms import ReviewCreateForm
from django.views import generic
from django.urls import reverse_lazy

# Create your views here.
class ReviewList(generic.ListView):
    model = Review

class ReviewDetail(generic.DetailView):
    model= Review

class ReviewCreate(generic.CreateView):
    model = Review
    form_class = ReviewCreateForm
    success_url = reverse_lazy('reviews:review_list')  

class ReviewUpdate(generic.UpdateView):
    model = Review
    form_class = ReviewCreateForm
    success_url = reverse_lazy('reviews:review_list')  

class ReviewDelete(generic.DeleteView):
    model = Review
    success_url = reverse_lazy('reviews:review_list')  



reviews/templates/reviews/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>いろんなお店の口コミサイト</title>
</head>
<body>
    <header>いろんなお店の口コミサイト</header>
<main>
    {% block content %}{% endblock %}
</main>
</body>
</html>

reviews/templates/reviews/review_confirm_delete.html
{% extends 'reviews/base.html' %}

{% block content %}
    <p>{{ review.store_name }}のレビューを削除します。よろしいですか。</p>
    <form action="" method="POST">
        {% csrf_token %}
        <button type="submit">削除</button>
    </form>
{% endblock %}

reviews/templates/reviews/review_detail.html
{% extends 'reviews/base.html' %}

{% block content %}
        <article>
            <h1>{{ review.store_name }}</h1>
            <p>{{ review.get_stars_display }} - {{ review.title }}</p>
            {{ review.text | linebreaks }}
        </article>
        <a href="{% url 'reviews:review_update' review.pk %}">更新</a>
        <a href="{% url 'reviews:review_delete' review.pk %}">削除</a>
{% endblock %}

reviews/templates/reviews/review_form.html
{% extends 'reviews/base.html' %}
{% block content %}
<form action="" method="POST">    
    {{ form.as_p }}
    {% csrf_token %}
    <button type="submit">送信</button>
</form>
    {% endblock %}

reviews/templates/reviews/review_list.html
{% extends 'reviews/base.html' %}

{% block content %}
    <h1>口コミ一覧</h1>
    {% for review in review_list %}
        <article>
            <h2><a href="{% url 'reviews:review_detail' review.pk %}">{{ review.store_name }}</a></h2>
            <p>{{ review.get_stars_display }} - {{ review.title }}</p>
        </article>
    {% endfor %}
    <a href="{% url 'reviews:review_create' %}">口コミ作成ページへ</a>
{% endblock %}