blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns =[
    path('',views.PostList.as_view(),name='post_list'),
    path('detail/<int:pk>/',views.PostDetail.as_view(),name='post_detail'),
    path('comment/<int:pk>',views.CommentCreate.as_view(),name='comment_create'),
]

myprofile/urls.py
from django.urls import path
from . import views

app_name='myprofile'

urlpatterns = [
    path('',views.top,name='top'),
    path('resume/',views.resume,name='resume'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diaries/',include('diaries.urls')),
    path('reviews/',include('reviews.urls')),
    path('contact/',include('contact.urls')),
    path('video/',include('video.urls')),
    path('blog/',include('blog.urls')),
    path('',include('myprofile.urls')),
]

urlpatterns += static(settings.MEDIA_URL,docment_root=settings.MEDIA_ROOT)

myprofile/models.py
from django.db import models

# Create your models here.

myprofile/views.py
from django.shortcuts import render

# Create your views here.
def top(request):
    context = {
        'name' : 'たかあき'
    }

    return render(request,'myprofile/top.html',context)

def resume(request):
    context = {
        'school' : '九州大学大学院'
    }

    return render(request,'myprofile/resume.html')

myprofile/templates/myprofile/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
</head>

<body>

<header>Takaaki's profile</header>

<nav>
    <a href="{% url 'myprofile:top' %}">TOP</a>
    <a href="{% url 'myprofile:resume' %}">Resume</a>
</nav>

{% block content %}{% endblock %}

</body>
</html>

myprofile/templates/myprofile/resume.html
{% extends 'myprofile/base.html' %}

{% block title %}Takao's profile{% endblock %}

{% block content %}
    <h1>{{ name }}についての概要</h1>
    <p>学と</p>

    <h2>趣味</h2>
    <table>
        <tr>
            <th>2015</th>
            <td>aidemy</td>
        </tr>
    </table>
{% endblock %}

myprofile/templates/myprofile/top.html
{% extends 'myprofile/base.html' %}

{% block title %}Takao's profile{% endblock %}

{% block content %}
    <h1>{{ name }}についての概要</h1>
    <p>学と</p>

    <h2>趣味</h2>
    <ul>
        <li>釣り</li>
        <li>sunobo</li>
    </ul>
{% endblock %}