blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns =[
    path('',views.PostList.as_view(),name='post_list'),
    path('detail/<int:pk>/',views.PostDetail.as_view(),name='post_detail'),
    path('comment/<int:pk>',views.CommentCreate.as_view(),name='comment_create'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diaries/',include('diaries.urls')),
    path('reviews/',include('reviews.urls')),
    path('contact/',include('contact.urls')),
    path('video/',include('video.urls')),
    path('blog/',include('blog.urls')),
    path('',include('myprofile.urls')),
]

urlpatterns += static(settings.MEDIA_URL,docment_root=settings.MEDIA_ROOT)

video/urls.py
from django.urls import path
from . import views

app_name = 'video'

urlpatterns =[
    path('',views.VideoList.as_view(),name='video_list'),
    path('create/',views.VideoCreate.as_view(),name='video_create'),
    path('play/<int:pk>/',views.VideoDetail.as_view(),name='video_detail')
]

video/models.py
from django.core.validators import FileExtensionValidator
from django.db import models

# Create your models here.
class Video(models.Model):
    title = models.CharField('動画タイトル',max_length=255)
    thumbnail = models.ImageField('動画サムネイル',blank=True)
    file = models.FileField('動画ファイル',validators=[FileExtensionValidator(allowed_extensions=['mp4','mov','mpeg','mpg','avi','wmv','flv',''])])

    def __str__(self):
        return self.title

video/views.py
from django.views import generic
from .models import Video
from django.urls import reverse_lazy
# Create your views here.

class VideoList(generic.ListView):
    model = Video

class VideoCreate(generic.CreateView):
    model = Video
    fields = '__all__'
    success_url = reverse_lazy('video:video_list')

class VideoDetail(generic.DetailView):
    model = Video

video/templates/video/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-wdith",initial-scale=1>
    <title>動画アップロード</title>
</head>
<body>
    {% block content %}{% endblock %}
</body>
<p>
    <a href="{% url 'video:video_list' %}">動画一覧</a>
    <a href="{% url 'video:video_create' %}">アップロード</a>
</p>
<br>
</html>

video/templates/video/video_detail.html
{% extends 'video/base.html' %}

{% block content %}
    <h1>{{ video.title }}</h1>
    <video src="{{ video.file.url }}" controls></video>
{% endblock %}

video/templates/video/video_form.html
{% extends 'video/base.html' %}
{% block content %}
    <form action="" method = "POST" enctype="multipart/form-data">
        {{ form.as_p }}
        {% csrf_token %}
        <button type="submit">送信</button>
    </form>
{% endblock %}

video/templates/video/video_list.html
{% extends 'video/base.html' %}

{% block content %}
    {% for video in video_list %}
        <a href="{% url 'video:video_detail' video.pk %}">
            <div class="video">
                {% if video.thumbnail %}
                    <img src="{{ video.thumbnail.url }}" >
                {% endif %}
                <h2>{{ video.title }}</h2>
            </div>
        </a>
    {% endfor %}
{% endblock %}