blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns =[
    path('',views.PostList.as_view(),name='post_list'),
    path('detail/<int:pk>/',views.PostDetail.as_view(),name='post_detail'),
    path('comment/<int:pk>',views.CommentCreate.as_view(),name='comment_create'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diaries/',include('diaries.urls')),
    path('reviews/',include('reviews.urls')),
    path('contact/',include('contact.urls')),
    path('video/',include('video.urls')),
    path('blog/',include('blog.urls')),
    path('',include('myprofile.urls')),
]

urlpatterns += static(settings.MEDIA_URL,docment_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Tag(models.Model):
    name = models.CharField('タグ名',max_length=255,unique=True)

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField('カテゴリ名',max_length=255,unique=True)

    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField('タイトル',max_length=32)
    text = models.TextField("本文")
    category = models.ForeignKey(Category,on_delete=models.PROTECT,verbose_name='カテゴリ')

    tags = models.ManyToManyField(Tag,verbose_name='タグ',blank=True)
    writer = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.PROTECT,verbose_name='投稿者')

    created_at = models.DateTimeField('作成日',auto_now_add=True)
    update_at = models.DateTimeField('更新日',auto_now=True)

    def __str__(self):
        return self.title
    
class Comment(models.Model):
    text = models.TextField("本文")
    target = models.ForeignKey(Post,on_delete=models.PROTECT,verbose_name='どの記事へのコメントか')

    def __str__(self):
        return self.text[:20]

blog/forms.py
from django import forms
from .models import Comment

class CommentCreateForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)
        widgets = {
            'text' : forms.Textarea(attrs={'class':'textarea'})
        }

blog/views.py
from django.views import generic
from .models import Post,Comment
from django.shortcuts import get_object_or_404,redirect
from django.urls import reverse_lazy
from .forms import CommentCreateForm

# Create your views here.
class PostList(generic.ListView):
    model = Post
    ordering = '-created_at'

class PostDetail(generic.DetailView):
    model = Post

class CommentCreate(generic.CreateView):
    model = Comment
    form_class = CommentCreateForm

    def form_valid(self, form):
        post_pk = self.kwargs['pk']
        post = get_object_or_404(Post, pk=post_pk)
        comment = form.save(commit=False)
        comment.target = post
        comment.save()
        return redirect('blog:post_detail',pk=post_pk)
        

blog/templates/blog/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Takablog</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.5/css/bluma.min.css">
    <script defer src="https://use.fontawesome.com/release/v5.3.1/js/all.js"></script>
</head>
<body>
<header class="hero is-primary">
    <div class="hero-body">
        <div class="container">
            <h1 class="title"><a href="{% url 'blog:post_list' %}" class="has-text-white">takablog</a></h1>
            <h2 class="subtitle">いろいろな記事を書いています</h2>
        </div>
    </div>
</header>

<div class="section">
    <div class="container">
        <div class="columns">
            <main class="column is-7">
                {% block content %}{% endblock %}
            </main>
            <aside class="column is-offset-1 is-4">
                <!-- サイドバ -->
            </aside>
        </div>
    </div>
</div>
</body>
</html>

blog/templates/blog/comment_form.html
{% extends 'blog/base.html' %}

{% block content %}
    <form action="">
    {{ form.non_field_errors }}
        {% for field in form %}
            <div class="field">
                <label class="label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                
                <div class="control">
                    {{ field }}
                    {% if field.help_text %}
                        <span class="helptext">{{ fields.help_text }}</span>
                    {% endif %}
                </div>
                {{ fields.errors }}
            </div>
        {% endfor %}
        {% csrf_token %}
        <button class="button is-primary" type="submit">送信</button>
    </form>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <article class="box">
        <h1>{{ post.title }}</h1>
        <p>投稿者 : {{ post.writer }} </p>
        <p>作成日 : {{ post.created_at }}</p>
        <p>更新日 : {{ post.updated_at }}</p>  
        <p>カテゴリ : {{ post.category }}</p>
        <p>タグ  {% for tag in post.tag.all %}{{tag}},{% endfor %}</p>
        <hr>
        <div>
            {{ post.text | linebreaks | urlize }}
        </div>
    </article>

    <a class="button is-primary" href="{% url 'blog:comment-create' post.pk %}">コメントする</a>

    <section class="section">
        {% for comment in post.comment_set.all %}
            <div class="box">
                {{ comment | linebreaks | urlize }}
            </div>
        {% endfor %}
    </section>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for post in post_list %}
        <article class="box">
            <h1><a href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a></h1>
            <p>投稿者 : {{ post.writer }} </p>
            <p>作成日 : {{ post.created_at }}</p>
            <p>更新日 : {{ post.updated_at }}</p>  
            <p>カテゴリ : {{ post.category }}</p>
            <p>タグ  {% for tag in post.tag.all %}{{tag}},{% endfor %}</p>
        </article>
    {% endfor %}
{% endblock %}